language: node_js
node_js:
  - "node"
addons:
  firefox: latest
  chrome: stable
script:
  - yarn build
  - yarn lint
  - yarn cypress install
  - yarn test
  - yarn test-e2e:firefox
  - yarn test-e2e:chrome
