language: node_js
node_js:
  - "node"
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.yarn
    - ~/.cache
addons:
  firefox: latest
script:
  - yarn build
  - yarn lint
  - yarn test
