export const nodeNames = {
  APPLICATION: 'application',
  ASSETS: 'assets',
  COMMENT: '#comment',
  DATA: 'data',
  DOCUMENT_TYPE: '#documentType',
  ELEMENT: 'element',
  FRAGMENT: 'fragment',
  NODE: 'node',
  REDIRECT: 'redirect',
  ROUTE: 'route',
  ROUTER: 'single-spa-router',
  ROUTER_CONTENT: 'ssl-router-content',
  TEXT: '#text',
} as const;
